// --------------- Statically Linked Functions ----------------

// __int64 __allmul(__int64 a, __int64 b);
// int32_t __aulldiv(void);
// int32_t __aullrem(void);
// int32_t __cintrindisp1(void);
// int32_t __cintrindisp2(void);
// int32_t __fload(int32_t a1, int32_t a2);
// int32_t __ftol(void);
// int32_t __global_unwind2(void);
// int32_t __local_unwind2(void);
// int32_t __ms_p5_mp_test_fdiv(void);
// int32_t __NLG_Notify(void);
// int32_t __trandisp1(char a1);
// int32_t __trandisp2(char a1);

// --------------- Dynamically Linked Functions ---------------

// long _hread(_In_ HFILE hFile, LPVOID lpBuffer, _In_ long lBytes);
// HFILE _lclose(_In_ HFILE hFile);
// LONG _llseek(_In_ HFILE hFile, _In_ LONG lOffset, _In_ int iOrigin);
// HFILE _lopen(_In_ LPCSTR lpPathName, _In_ int iReadWrite);
// UINT _lread(_In_ HFILE hFile, LPVOID lpBuffer, _In_ UINT uBytes);
// HDC BeginPaint(_In_ HWND hWnd, _Out_ LPPAINTSTRUCT lpPaint);
// BOOL BitBlt(_In_ HDC hdc, _In_ int x, _In_ int y, _In_ int cx, _In_ int cy, _In_opt_ HDC hdcSrc, _In_ int x1, _In_ int y1, _In_ DWORD rop);
// LONG ChangeDisplaySettingsA(_In_opt_ DEVMODEA * lpDevMode, _In_ DWORD dwFlags);
// DWORD CheckMenuItem(_In_ HMENU hMenu, _In_ UINT uIDCheckItem, _In_ UINT uCheck);
// BOOL CloseHandle(_In_ HANDLE hObject);
// HBITMAP CreateCompatibleBitmap(_In_ HDC hdc, _In_ int cx, _In_ int cy);
// HDC CreateCompatibleDC(_In_opt_ HDC hdc);
// HBITMAP CreateDIBitmap(_In_ HDC hdc, _In_opt_ const BITMAPINFOHEADER * pbmih, _In_ DWORD flInit, _In_opt_ const VOID * pjBits, _In_opt_ const BITMAPINFO * pbmi, _In_ UINT iUsage);
// HANDLE CreateFileA(_In_ LPCSTR lpFileName, _In_ DWORD dwDesiredAccess, _In_ DWORD dwShareMode, _In_opt_ LPSECURITY_ATTRIBUTES lpSecurityAttributes, _In_ DWORD dwCreationDisposition, _In_ DWORD dwFlagsAndAttributes, _In_opt_ HANDLE hTemplateFile);
// HPALETTE CreatePalette(const LOGPALETTE * plpal);
// HBRUSH CreateSolidBrush(_In_ COLORREF color);
// HWND CreateWindowExA(_In_ DWORD dwExStyle, _In_opt_ LPCSTR lpClassName, _In_opt_ LPCSTR lpWindowName, _In_ DWORD dwStyle, _In_ int X, _In_ int Y, _In_ int nWidth, _In_ int nHeight, _In_opt_ HWND hWndParent, _In_opt_ HMENU hMenu, _In_opt_ HINSTANCE hInstance, _In_opt_ LPVOID lpParam);
// LRESULT DefWindowProcA(_In_ HWND hWnd, _In_ UINT Msg, _In_ WPARAM wParam, _In_ LPARAM lParam);
// VOID DeleteCriticalSection(_Inout_ LPCRITICAL_SECTION lpCriticalSection);
// BOOL DeleteDC(_In_ HDC hdc);
// BOOL DeleteMenu(_In_ HMENU hMenu, _In_ UINT uPosition, _In_ UINT uFlags);
// BOOL DeleteObject(_In_ HGDIOBJ ho);
// BOOL DestroyWindow(_In_ HWND hWnd);
// INT_PTR DialogBoxIndirectParamA(_In_opt_ HINSTANCE hInstance, _In_ LPCDLGTEMPLATEA hDialogTemplate, _In_opt_ HWND hWndParent, _In_opt_ DLGPROC lpDialogFunc, _In_ LPARAM dwInitParam);
// INT_PTR DialogBoxParamA(_In_opt_ HINSTANCE hInstance, _In_ LPCSTR lpTemplateName, _In_opt_ HWND hWndParent, _In_opt_ DLGPROC lpDialogFunc, _In_ LPARAM dwInitParam);
// LRESULT DispatchMessageA(_In_ const MSG * lpMsg);
// BOOL DrawMenuBar(_In_ HWND hWnd);
// int DrawTextA(_In_ HDC hdc, LPCSTR lpchText, _In_ int cchText, _Inout_ LPRECT lprc, _In_ UINT format);
// BOOL EnableMenuItem(_In_ HMENU hMenu, _In_ UINT uIDEnableItem, _In_ UINT uEnable);
// BOOL EnableWindow(_In_ HWND hWnd, _In_ BOOL bEnable);
// BOOL EndDialog(_In_ HWND hDlg, _In_ INT_PTR nResult);
// BOOL EndPaint(_In_ HWND hWnd, _In_ const PAINTSTRUCT * lpPaint);
// VOID EnterCriticalSection(_Inout_ LPCRITICAL_SECTION lpCriticalSection);
// VOID ExitProcess(_In_ UINT uExitCode);
// int FillRect(_In_ HDC hDC, _In_ const RECT * lprc, _In_ HBRUSH hbr);
// HRSRC FindResourceA(_In_opt_ HMODULE hModule, _In_ LPCSTR lpName, _In_ LPCSTR lpType);
// HWND FindWindowA(_In_opt_ LPCSTR lpClassName, _In_opt_ LPCSTR lpWindowName);
// BOOL FlushFileBuffers(_In_ HANDLE hFile);
// BOOL FreeEnvironmentStringsA(_In_ LPCH penv);
// BOOL FreeEnvironmentStringsW(_In_ LPWCH penv);
// BOOL FreeResource(_In_ HGLOBAL hResData);
// UINT GetACP(void);
// LPSTR GetCommandLineA(VOID);
// BOOL GetCPInfo(_In_ UINT CodePage, _Out_ LPCPINFO lpCPInfo);
// HANDLE GetCurrentProcess(VOID);
// HANDLE GetCurrentThread(VOID);
// DWORD GetCurrentThreadId(VOID);
// BOOL GetCursorPos(_Out_ LPPOINT lpPoint);
// HDC GetDC(_In_opt_ HWND hWnd);
// HWND GetDesktopWindow(VOID);
// int GetDeviceCaps(_In_opt_ HDC hdc, _In_ int index);
// HWND GetDlgItem(_In_opt_ HWND hDlg, _In_ int nIDDlgItem);
// UINT GetDlgItemTextA(_In_ HWND hDlg, _In_ int nIDDlgItem, LPSTR lpString, _In_ int cchMax);
// LPCH GetEnvironmentStrings(VOID);
// LPWCH GetEnvironmentStringsW(void);
// DWORD GetFileType(_In_ HANDLE hFile);
// int GetKeyNameTextA(_In_ LONG lParam, LPSTR lpString, _In_ int cchSize);
// DWORD GetLastError(VOID);
// int GetLocaleInfoA(_In_ LCID Locale, _In_ LCTYPE LCType, LPSTR lpLCData, _In_ int cchData);
// int GetLocaleInfoW(_In_ LCID Locale, _In_ LCTYPE LCType, LPWSTR lpLCData, _In_ int cchData);
// HMENU GetMenu(_In_ HWND hWnd);
// BOOL GetMessageA(_Out_ LPMSG lpMsg, _In_opt_ HWND hWnd, _In_ UINT wMsgFilterMin, _In_ UINT wMsgFilterMax);
// DWORD GetModuleFileNameA(_In_opt_ HMODULE hModule, LPSTR lpFilename, _In_ DWORD nSize);
// HMODULE GetModuleHandleA(_In_opt_ LPCSTR lpModuleName);
// int GetObjectA(_In_ HANDLE h, _In_ int c, LPVOID pv);
// UINT GetOEMCP(void);
// UINT GetPaletteEntries(_In_ HPALETTE hpal, _In_ UINT iStart, _In_ UINT cEntries, LPPALETTEENTRY pPalEntries);
// HWND GetParent(_In_ HWND hWnd);
// UINT GetPrivateProfileIntA(_In_ LPCSTR lpAppName, _In_ LPCSTR lpKeyName, _In_ INT nDefault, _In_opt_ LPCSTR lpFileName);
// FARPROC GetProcAddress(_In_ HMODULE hModule, _In_ LPCSTR lpProcName);
// VOID GetStartupInfoA(_Out_ LPSTARTUPINFOA lpStartupInfo);
// HANDLE GetStdHandle(_In_ DWORD nStdHandle);
// HGDIOBJ GetStockObject(_In_ int i);
// BOOL GetStringTypeA(_In_ LCID Locale, _In_ DWORD dwInfoType, LPCSTR lpSrcStr, _In_ int cchSrc, _Out_ LPWORD lpCharType);
// BOOL GetStringTypeW(_In_ DWORD dwInfoType, LPCWCH lpSrcStr, _In_ int cchSrc, _Out_ LPWORD lpCharType);
// int GetSystemMetrics(_In_ int nIndex);
// UINT GetSystemPaletteEntries(_In_ HDC hdc, _In_ UINT iStart, _In_ UINT cEntries, LPPALETTEENTRY pPalEntries);
// DWORD GetTimeZoneInformation(_Out_ LPTIME_ZONE_INFORMATION lpTimeZoneInformation);
// NOT_BUILD_WINDOWS_DEPRECATE DWORD GetVersion(VOID);
// LONG GetWindowLongA(_In_ HWND hWnd, _In_ int nIndex);
// BOOL GetWindowRect(_In_ HWND hWnd, _Out_ LPRECT lpRect);
// int GetWindowTextA(_In_ HWND hWnd, LPSTR lpString, _In_ int nMaxCount);
// HGLOBAL GlobalAlloc(_In_ UINT uFlags, _In_ SIZE_T dwBytes);
// HGLOBAL GlobalFree(HGLOBAL hMem);
// HGLOBAL GlobalHandle(_In_ LPCVOID pMem);
// LPVOID GlobalLock(_In_ HGLOBAL hMem);
// HGLOBAL GlobalReAlloc(HGLOBAL hMem, _In_ SIZE_T dwBytes, _In_ UINT uFlags);
// BOOL GlobalUnlock(_In_ HGLOBAL hMem);
// LPVOID HeapAlloc(_In_ HANDLE hHeap, _In_ DWORD dwFlags, _In_ SIZE_T dwBytes);
// HANDLE HeapCreate(_In_ DWORD flOptions, _In_ SIZE_T dwInitialSize, _In_ SIZE_T dwMaximumSize);
// BOOL HeapDestroy(_In_ HANDLE hHeap);
// BOOL HeapFree(_Inout_ HANDLE hHeap, _In_ DWORD dwFlags, LPVOID lpMem);
// LPVOID HeapReAlloc(_Inout_ HANDLE hHeap, _In_ DWORD dwFlags, LPVOID lpMem, _In_ SIZE_T dwBytes);
// VOID InitializeCriticalSection(_Out_ LPCRITICAL_SECTION lpCriticalSection);
// BOOL InvalidateRect(_In_opt_ HWND hWnd, _In_opt_ const RECT * lpRect, _In_ BOOL bErase);
// BOOL IsIconic(_In_ HWND hWnd);
// BOOL IsWindowVisible(_In_ HWND hWnd);
// int LCMapStringA(_In_ LCID Locale, _In_ DWORD dwMapFlags, LPCSTR lpSrcStr, _In_ int cchSrc, LPSTR lpDestStr, _In_ int cchDest);
// int LCMapStringW(_In_ LCID Locale, _In_ DWORD dwMapFlags, LPCWSTR lpSrcStr, _In_ int cchSrc, LPWSTR lpDestStr, _In_ int cchDest);
// VOID LeaveCriticalSection(_Inout_ LPCRITICAL_SECTION lpCriticalSection);
// HBITMAP LoadBitmapA(_In_opt_ HINSTANCE hInstance, _In_ LPCSTR lpBitmapName);
// HCURSOR LoadCursorA(_In_opt_ HINSTANCE hInstance, _In_ LPCSTR lpCursorName);
// HICON LoadIconA(_In_opt_ HINSTANCE hInstance, _In_ LPCSTR lpIconName);
// HMODULE LoadLibraryA(_In_ LPCSTR lpLibFileName);
// HGLOBAL LoadResource(_In_opt_ HMODULE hModule, _In_ HRSRC hResInfo);
// int LoadStringA(_In_opt_ HINSTANCE hInstance, _In_ UINT uID, LPSTR lpBuffer, _In_ int cchBufferMax);
// HLOCAL LocalAlloc(_In_ UINT uFlags, _In_ SIZE_T uBytes);
// HLOCAL LocalFree(HLOCAL hMem);
// LPVOID LockResource(_In_ HGLOBAL hResData);
// LPSTR lstrcatA(LPSTR lpString1, _In_ LPCSTR lpString2);
// int lstrcmpA(_In_ LPCSTR lpString1, _In_ LPCSTR lpString2);
// LPSTR lstrcpyA(LPSTR lpString1, _In_ LPCSTR lpString2);
// LPSTR lstrcpynA(LPSTR lpString1, _In_ LPCSTR lpString2, _In_ int iMaxLength);
// int lstrlenA(_In_ LPCSTR lpString);
// UINT MapVirtualKeyA(_In_ UINT uCode, _In_ UINT uMapType);
// MCIERROR mciSendCommandA(_In_ MCIDEVICEID mciId, _In_ UINT uMsg, _In_opt_ DWORD_PTR dwParam1, _In_opt_ DWORD_PTR dwParam2);
// BOOL MessageBeep(_In_ UINT uType);
// int MessageBoxA(_In_opt_ HWND hWnd, _In_opt_ LPCSTR lpText, _In_opt_ LPCSTR lpCaption, _In_ UINT uType);
// MMRESULT mmioAscend(_In_ HMMIO hmmio, _In_ LPMMCKINFO pmmcki, _In_ UINT fuAscend);
// MMRESULT mmioClose(_In_ HMMIO hmmio, _In_ UINT fuClose);
// MMRESULT mmioDescend(_In_ HMMIO hmmio, _Inout_ LPMMCKINFO pmmcki, _In_opt_ const MMCKINFO * pmmckiParent, _In_ UINT fuDescend);
// HMMIO mmioOpenA(LPSTR pszFileName, _Inout_opt_ LPMMIOINFO pmmioinfo, _In_ DWORD fdwOpen);
// LONG mmioRead(_In_ HMMIO hmmio, HPSTR pch, _In_ LONG cch);
// BOOL MoveWindow(_In_ HWND hWnd, _In_ int X, _In_ int Y, _In_ int nWidth, _In_ int nHeight, _In_ BOOL bRepaint);
// int MultiByteToWideChar(_In_ UINT CodePage, _In_ DWORD dwFlags, LPCCH lpMultiByteStr, _In_ int cbMultiByte, LPWSTR lpWideCharStr, _In_ int cchWideChar);
// HFILE OpenFile(_In_ LPCSTR lpFileName, _Inout_ LPOFSTRUCT lpReOpenBuff, _In_ UINT uStyle);
// BOOL PeekMessageA(_Out_ LPMSG lpMsg, _In_opt_ HWND hWnd, _In_ UINT wMsgFilterMin, _In_ UINT wMsgFilterMax, _In_ UINT wRemoveMsg);
// BOOL PostMessageA(_In_opt_ HWND hWnd, _In_ UINT Msg, _In_ WPARAM wParam, _In_ LPARAM lParam);
// VOID PostQuitMessage(_In_ int nExitCode);
// VOID RaiseException(_In_ DWORD dwExceptionCode, _In_ DWORD dwExceptionFlags, _In_ DWORD nNumberOfArguments, const ULONG_PTR * lpArguments);
// BOOL ReadFile(_In_ HANDLE hFile, LPVOID lpBuffer, _In_ DWORD nNumberOfBytesToRead, _Out_opt_ LPDWORD lpNumberOfBytesRead, _Inout_opt_ LPOVERLAPPED lpOverlapped);
// UINT RealizePalette(_In_ HDC hdc);
// BOOL RedrawWindow(_In_opt_ HWND hWnd, _In_opt_ const RECT * lprcUpdate, _In_opt_ HRGN hrgnUpdate, _In_ UINT flags);
// LSTATUS RegCloseKey(_In_ HKEY hKey);
// LSTATUS RegCreateKeyExA(_In_ HKEY hKey, _In_ LPCSTR lpSubKey, DWORD Reserved, _In_opt_ LPSTR lpClass, _In_ DWORD dwOptions, _In_ REGSAM samDesired, _In_opt_ const LPSECURITY_ATTRIBUTES lpSecurityAttributes, _Out_ PHKEY phkResult, _Out_opt_ LPDWORD lpdwDisposition);
// ATOM RegisterClassA(_In_ const WNDCLASSA * lpWndClass);
// UINT RegisterWindowMessageA(_In_ LPCSTR lpString);
// LSTATUS RegOpenKeyA(_In_ HKEY hKey, _In_opt_ LPCSTR lpSubKey, _Out_ PHKEY phkResult);
// LSTATUS RegQueryValueA(_In_ HKEY hKey, _In_opt_ LPCSTR lpSubKey, LPSTR lpData, _Inout_opt_ PLONG lpcbData);
// LSTATUS RegQueryValueExA(_In_ HKEY hKey, _In_opt_ LPCSTR lpValueName, LPDWORD lpReserved, _Out_opt_ LPDWORD lpType, LPBYTE lpData, LPDWORD lpcbData);
// LSTATUS RegSetValueExA(_In_ HKEY hKey, _In_opt_ LPCSTR lpValueName, DWORD Reserved, _In_ DWORD dwType, const BYTE * lpData, _In_ DWORD cbData);
// BOOL ReleaseCapture(VOID);
// int ReleaseDC(_In_opt_ HWND hWnd, _In_ HDC hDC);
// BOOL ResizePalette(_In_ HPALETTE hpal, _In_ UINT n);
// VOID RtlUnwind(_In_opt_ PVOID TargetFrame, _In_opt_ PVOID TargetIp, _In_opt_ PEXCEPTION_RECORD ExceptionRecord, _In_ PVOID ReturnValue);
// HGDIOBJ SelectObject(_In_ HDC hdc, _In_ HGDIOBJ h);
// HPALETTE SelectPalette(_In_ HDC hdc, _In_ HPALETTE hPal, _In_ BOOL bForceBkgd);
// LRESULT SendDlgItemMessageA(_In_ HWND hDlg, _In_ int nIDDlgItem, _In_ UINT Msg, _In_ WPARAM wParam, _In_ LPARAM lParam);
// LRESULT SendMessageA(_In_ HWND hWnd, _In_ UINT Msg, WPARAM wParam, LPARAM lParam);
// int SetBkMode(_In_ HDC hdc, _In_ int mode);
// HWND SetCapture(_In_ HWND hWnd);
// HCURSOR SetCursor(_In_opt_ HCURSOR hCursor);
// BOOL SetCursorPos(_In_ int X, _In_ int Y);
// BOOL SetEndOfFile(_In_ HANDLE hFile);
// DWORD SetFilePointer(_In_ HANDLE hFile, _In_ LONG lDistanceToMove, _Inout_opt_ PLONG lpDistanceToMoveHigh, _In_ DWORD dwMoveMethod);
// HWND SetFocus(_In_opt_ HWND hWnd);
// BOOL SetForegroundWindow(_In_ HWND hWnd);
// UINT SetHandleCount(_In_ UINT uNumber);
// VOID SetLastError(_In_ DWORD dwErrCode);
// BOOL SetMenu(_In_ HWND hWnd, _In_opt_ HMENU hMenu);
// UINT SetPaletteEntries(_In_ HPALETTE hpal, _In_ UINT iStart, _In_ UINT cEntries, const PALETTEENTRY * pPalEntries);
// BOOL SetStdHandle(_In_ DWORD nStdHandle, _In_ HANDLE hHandle);
// UINT SetSystemPaletteUse(_In_ HDC hdc, _In_ UINT use);
// COLORREF SetTextColor(_In_ HDC hdc, _In_ COLORREF color);
// BOOL SetThreadPriority(_In_ HANDLE hThread, _In_ int nPriority);
// LONG SetWindowLongA(_In_ HWND hWnd, _In_ int nIndex, _In_ LONG dwNewLong);
// BOOL SetWindowPos(_In_ HWND hWnd, _In_opt_ HWND hWndInsertAfter, _In_ int X, _In_ int Y, _In_ int cx, _In_ int cy, _In_ UINT uFlags);
// BOOL SetWindowTextA(_In_ HWND hWnd, _In_opt_ LPCSTR lpString);
// BOOL ShowWindow(_In_ HWND hWnd, _In_ int nCmdShow);
// DWORD SizeofResource(_In_opt_ HMODULE hModule, _In_ HRSRC hResInfo);
// BOOL sndPlaySoundA(_In_opt_ LPCSTR pszSound, _In_ UINT fuSound);
// int StretchDIBits(_In_ HDC hdc, _In_ int xDest, _In_ int yDest, _In_ int DestWidth, _In_ int DestHeight, _In_ int xSrc, _In_ int ySrc, _In_ int SrcWidth, _In_ int SrcHeight, _In_opt_ const VOID * lpBits, _In_ const BITMAPINFO * lpbmi, _In_ UINT iUsage, _In_ DWORD rop);
// BOOL TerminateProcess(_In_ HANDLE hProcess, _In_ UINT uExitCode);
// DWORD timeGetTime(void);
// DWORD TlsAlloc(VOID);
// LPVOID TlsGetValue(_In_ DWORD dwTlsIndex);
// BOOL TlsSetValue(_In_ DWORD dwTlsIndex, _In_opt_ LPVOID lpTlsValue);
// BOOL TranslateMessage(_In_ const MSG * lpMsg);
// LONG UnhandledExceptionFilter(_In_ struct _EXCEPTION_POINTERS * ExceptionInfo);
// BOOL UnregisterClassA(_In_ LPCSTR lpClassName, _In_opt_ HINSTANCE hInstance);
// BOOL UpdateWindow(_In_ HWND hWnd);
// LPVOID VirtualAlloc(_In_opt_ LPVOID lpAddress, _In_ SIZE_T dwSize, _In_ DWORD flAllocationType, _In_ DWORD flProtect);
// BOOL VirtualFree(LPVOID lpAddress, _In_ SIZE_T dwSize, _In_ DWORD dwFreeType);
// MMRESULT waveOutClose(_In_ HWAVEOUT hwo);
// MMRESULT waveOutGetDevCapsA(_In_ UINT_PTR uDeviceID, _Out_ LPWAVEOUTCAPSA pwoc, _In_ UINT cbwoc);
// UINT waveOutGetNumDevs(void);
// MMRESULT waveOutGetPosition(_In_ HWAVEOUT hwo, LPMMTIME pmmt, _In_ UINT cbmmt);
// MMRESULT waveOutOpen(_Out_opt_ LPHWAVEOUT phwo, _In_ UINT uDeviceID, _In_ LPCWAVEFORMATEX pwfx, _In_opt_ DWORD_PTR dwCallback, _In_opt_ DWORD_PTR dwInstance, _In_ DWORD fdwOpen);
// MMRESULT waveOutPause(_In_ HWAVEOUT hwo);
// MMRESULT waveOutPrepareHeader(_In_ HWAVEOUT hwo, LPWAVEHDR pwh, _In_ UINT cbwh);
// MMRESULT waveOutReset(_In_ HWAVEOUT hwo);
// MMRESULT waveOutRestart(_In_ HWAVEOUT hwo);
// MMRESULT waveOutUnprepareHeader(_In_ HWAVEOUT hwo, LPWAVEHDR pwh, _In_ UINT cbwh);
// MMRESULT waveOutWrite(_In_ HWAVEOUT hwo, LPWAVEHDR pwh, _In_ UINT cbwh);
// int WideCharToMultiByte(_In_ UINT CodePage, _In_ DWORD dwFlags, LPCWCH lpWideCharStr, _In_ int cchWideChar, LPSTR lpMultiByteStr, _In_ int cbMultiByte, _In_opt_ LPCCH lpDefaultChar, _Out_opt_ LPBOOL lpUsedDefaultChar);
// UINT WinExec(_In_ LPCSTR lpCmdLine, _In_ UINT uCmdShow);
// BOOL WinHelpA(_In_opt_ HWND hWndMain, _In_opt_ LPCSTR lpszHelp, _In_ UINT uCommand, _In_ ULONG_PTR dwData);
// BOOL WriteFile(_In_ HANDLE hFile, LPCVOID lpBuffer, _In_ DWORD nNumberOfBytesToWrite, _Out_opt_ LPDWORD lpNumberOfBytesWritten, _Inout_opt_ LPOVERLAPPED lpOverlapped);
// BOOL WritePrivateProfileStringA(_In_opt_ LPCSTR lpAppName, _In_opt_ LPCSTR lpKeyName, _In_opt_ LPCSTR lpString, _In_opt_ LPCSTR lpFileName);
// int wsprintfA(_Out_ LPSTR, _In_ LPCSTR, ...);

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: msvc (4.x)
// Detected language: C++
// Detected functions: 915
// Decompilation date: 2019-07-08 00:18:28
